//! Product route table: matchRoute/handle across ALL route_shard_*.
const std = @import("std");
const g = @import("generated_root.zig");

pub const Matched = struct { method: []const u8, path: []const u8, name: []const u8, shard: u32 };

pub fn matchRoute(method: []const u8, path: []const u8) ?Matched {
    if (g.route_shard_0.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 0 };
    }
    if (g.route_shard_1.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 1 };
    }
    if (g.route_shard_2.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 2 };
    }
    if (g.route_shard_3.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 3 };
    }
    if (g.route_shard_4.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 4 };
    }
    if (g.route_shard_5.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 5 };
    }
    if (g.route_shard_6.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 6 };
    }
    if (g.route_shard_7.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 7 };
    }
    if (g.route_shard_8.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 8 };
    }
    if (g.route_shard_9.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 9 };
    }
    if (g.route_shard_10.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 10 };
    }
    if (g.route_shard_11.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 11 };
    }
    if (g.route_shard_12.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 12 };
    }
    if (g.route_shard_13.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 13 };
    }
    if (g.route_shard_14.matchRoute(method, path)) |r| {
        return .{ .method = r.method, .path = r.path, .name = r.name, .shard = 14 };
    }
    return null;
}

pub fn handleExt(gpa: std.mem.Allocator, path: []const u8, body: []const u8) !?[]u8 {
    if (std.mem.eql(u8, path, "/ext/0/0")) return try g.route_shard_0.handle_ext_0_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/1")) return try g.route_shard_0.handle_ext_0_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/2")) return try g.route_shard_0.handle_ext_0_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/3")) return try g.route_shard_0.handle_ext_0_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/4")) return try g.route_shard_0.handle_ext_0_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/5")) return try g.route_shard_0.handle_ext_0_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/6")) return try g.route_shard_0.handle_ext_0_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/7")) return try g.route_shard_0.handle_ext_0_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/8")) return try g.route_shard_0.handle_ext_0_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/9")) return try g.route_shard_0.handle_ext_0_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/10")) return try g.route_shard_0.handle_ext_0_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/11")) return try g.route_shard_0.handle_ext_0_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/12")) return try g.route_shard_0.handle_ext_0_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/13")) return try g.route_shard_0.handle_ext_0_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/14")) return try g.route_shard_0.handle_ext_0_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/15")) return try g.route_shard_0.handle_ext_0_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/16")) return try g.route_shard_0.handle_ext_0_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/17")) return try g.route_shard_0.handle_ext_0_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/18")) return try g.route_shard_0.handle_ext_0_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/19")) return try g.route_shard_0.handle_ext_0_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/20")) return try g.route_shard_0.handle_ext_0_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/21")) return try g.route_shard_0.handle_ext_0_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/22")) return try g.route_shard_0.handle_ext_0_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/23")) return try g.route_shard_0.handle_ext_0_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/24")) return try g.route_shard_0.handle_ext_0_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/25")) return try g.route_shard_0.handle_ext_0_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/26")) return try g.route_shard_0.handle_ext_0_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/27")) return try g.route_shard_0.handle_ext_0_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/28")) return try g.route_shard_0.handle_ext_0_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/29")) return try g.route_shard_0.handle_ext_0_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/30")) return try g.route_shard_0.handle_ext_0_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/31")) return try g.route_shard_0.handle_ext_0_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/32")) return try g.route_shard_0.handle_ext_0_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/33")) return try g.route_shard_0.handle_ext_0_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/34")) return try g.route_shard_0.handle_ext_0_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/35")) return try g.route_shard_0.handle_ext_0_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/36")) return try g.route_shard_0.handle_ext_0_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/37")) return try g.route_shard_0.handle_ext_0_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/38")) return try g.route_shard_0.handle_ext_0_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/39")) return try g.route_shard_0.handle_ext_0_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/40")) return try g.route_shard_0.handle_ext_0_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/41")) return try g.route_shard_0.handle_ext_0_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/42")) return try g.route_shard_0.handle_ext_0_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/43")) return try g.route_shard_0.handle_ext_0_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/44")) return try g.route_shard_0.handle_ext_0_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/45")) return try g.route_shard_0.handle_ext_0_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/46")) return try g.route_shard_0.handle_ext_0_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/47")) return try g.route_shard_0.handle_ext_0_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/48")) return try g.route_shard_0.handle_ext_0_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/0/49")) return try g.route_shard_0.handle_ext_0_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/0")) return try g.route_shard_1.handle_ext_1_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/1")) return try g.route_shard_1.handle_ext_1_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/2")) return try g.route_shard_1.handle_ext_1_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/3")) return try g.route_shard_1.handle_ext_1_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/4")) return try g.route_shard_1.handle_ext_1_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/5")) return try g.route_shard_1.handle_ext_1_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/6")) return try g.route_shard_1.handle_ext_1_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/7")) return try g.route_shard_1.handle_ext_1_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/8")) return try g.route_shard_1.handle_ext_1_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/9")) return try g.route_shard_1.handle_ext_1_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/10")) return try g.route_shard_1.handle_ext_1_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/11")) return try g.route_shard_1.handle_ext_1_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/12")) return try g.route_shard_1.handle_ext_1_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/13")) return try g.route_shard_1.handle_ext_1_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/14")) return try g.route_shard_1.handle_ext_1_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/15")) return try g.route_shard_1.handle_ext_1_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/16")) return try g.route_shard_1.handle_ext_1_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/17")) return try g.route_shard_1.handle_ext_1_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/18")) return try g.route_shard_1.handle_ext_1_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/19")) return try g.route_shard_1.handle_ext_1_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/20")) return try g.route_shard_1.handle_ext_1_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/21")) return try g.route_shard_1.handle_ext_1_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/22")) return try g.route_shard_1.handle_ext_1_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/23")) return try g.route_shard_1.handle_ext_1_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/24")) return try g.route_shard_1.handle_ext_1_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/25")) return try g.route_shard_1.handle_ext_1_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/26")) return try g.route_shard_1.handle_ext_1_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/27")) return try g.route_shard_1.handle_ext_1_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/28")) return try g.route_shard_1.handle_ext_1_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/29")) return try g.route_shard_1.handle_ext_1_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/30")) return try g.route_shard_1.handle_ext_1_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/31")) return try g.route_shard_1.handle_ext_1_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/32")) return try g.route_shard_1.handle_ext_1_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/33")) return try g.route_shard_1.handle_ext_1_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/34")) return try g.route_shard_1.handle_ext_1_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/35")) return try g.route_shard_1.handle_ext_1_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/36")) return try g.route_shard_1.handle_ext_1_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/37")) return try g.route_shard_1.handle_ext_1_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/38")) return try g.route_shard_1.handle_ext_1_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/39")) return try g.route_shard_1.handle_ext_1_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/40")) return try g.route_shard_1.handle_ext_1_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/41")) return try g.route_shard_1.handle_ext_1_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/42")) return try g.route_shard_1.handle_ext_1_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/43")) return try g.route_shard_1.handle_ext_1_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/44")) return try g.route_shard_1.handle_ext_1_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/45")) return try g.route_shard_1.handle_ext_1_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/46")) return try g.route_shard_1.handle_ext_1_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/47")) return try g.route_shard_1.handle_ext_1_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/48")) return try g.route_shard_1.handle_ext_1_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/1/49")) return try g.route_shard_1.handle_ext_1_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/0")) return try g.route_shard_2.handle_ext_2_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/1")) return try g.route_shard_2.handle_ext_2_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/2")) return try g.route_shard_2.handle_ext_2_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/3")) return try g.route_shard_2.handle_ext_2_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/4")) return try g.route_shard_2.handle_ext_2_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/5")) return try g.route_shard_2.handle_ext_2_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/6")) return try g.route_shard_2.handle_ext_2_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/7")) return try g.route_shard_2.handle_ext_2_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/8")) return try g.route_shard_2.handle_ext_2_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/9")) return try g.route_shard_2.handle_ext_2_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/10")) return try g.route_shard_2.handle_ext_2_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/11")) return try g.route_shard_2.handle_ext_2_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/12")) return try g.route_shard_2.handle_ext_2_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/13")) return try g.route_shard_2.handle_ext_2_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/14")) return try g.route_shard_2.handle_ext_2_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/15")) return try g.route_shard_2.handle_ext_2_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/16")) return try g.route_shard_2.handle_ext_2_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/17")) return try g.route_shard_2.handle_ext_2_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/18")) return try g.route_shard_2.handle_ext_2_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/19")) return try g.route_shard_2.handle_ext_2_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/20")) return try g.route_shard_2.handle_ext_2_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/21")) return try g.route_shard_2.handle_ext_2_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/22")) return try g.route_shard_2.handle_ext_2_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/23")) return try g.route_shard_2.handle_ext_2_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/24")) return try g.route_shard_2.handle_ext_2_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/25")) return try g.route_shard_2.handle_ext_2_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/26")) return try g.route_shard_2.handle_ext_2_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/27")) return try g.route_shard_2.handle_ext_2_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/28")) return try g.route_shard_2.handle_ext_2_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/29")) return try g.route_shard_2.handle_ext_2_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/30")) return try g.route_shard_2.handle_ext_2_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/31")) return try g.route_shard_2.handle_ext_2_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/32")) return try g.route_shard_2.handle_ext_2_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/33")) return try g.route_shard_2.handle_ext_2_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/34")) return try g.route_shard_2.handle_ext_2_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/35")) return try g.route_shard_2.handle_ext_2_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/36")) return try g.route_shard_2.handle_ext_2_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/37")) return try g.route_shard_2.handle_ext_2_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/38")) return try g.route_shard_2.handle_ext_2_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/39")) return try g.route_shard_2.handle_ext_2_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/40")) return try g.route_shard_2.handle_ext_2_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/41")) return try g.route_shard_2.handle_ext_2_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/42")) return try g.route_shard_2.handle_ext_2_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/43")) return try g.route_shard_2.handle_ext_2_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/44")) return try g.route_shard_2.handle_ext_2_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/45")) return try g.route_shard_2.handle_ext_2_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/46")) return try g.route_shard_2.handle_ext_2_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/47")) return try g.route_shard_2.handle_ext_2_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/48")) return try g.route_shard_2.handle_ext_2_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/2/49")) return try g.route_shard_2.handle_ext_2_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/0")) return try g.route_shard_3.handle_ext_3_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/1")) return try g.route_shard_3.handle_ext_3_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/2")) return try g.route_shard_3.handle_ext_3_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/3")) return try g.route_shard_3.handle_ext_3_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/4")) return try g.route_shard_3.handle_ext_3_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/5")) return try g.route_shard_3.handle_ext_3_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/6")) return try g.route_shard_3.handle_ext_3_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/7")) return try g.route_shard_3.handle_ext_3_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/8")) return try g.route_shard_3.handle_ext_3_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/9")) return try g.route_shard_3.handle_ext_3_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/10")) return try g.route_shard_3.handle_ext_3_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/11")) return try g.route_shard_3.handle_ext_3_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/12")) return try g.route_shard_3.handle_ext_3_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/13")) return try g.route_shard_3.handle_ext_3_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/14")) return try g.route_shard_3.handle_ext_3_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/15")) return try g.route_shard_3.handle_ext_3_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/16")) return try g.route_shard_3.handle_ext_3_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/17")) return try g.route_shard_3.handle_ext_3_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/18")) return try g.route_shard_3.handle_ext_3_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/19")) return try g.route_shard_3.handle_ext_3_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/20")) return try g.route_shard_3.handle_ext_3_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/21")) return try g.route_shard_3.handle_ext_3_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/22")) return try g.route_shard_3.handle_ext_3_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/23")) return try g.route_shard_3.handle_ext_3_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/24")) return try g.route_shard_3.handle_ext_3_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/25")) return try g.route_shard_3.handle_ext_3_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/26")) return try g.route_shard_3.handle_ext_3_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/27")) return try g.route_shard_3.handle_ext_3_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/28")) return try g.route_shard_3.handle_ext_3_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/29")) return try g.route_shard_3.handle_ext_3_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/30")) return try g.route_shard_3.handle_ext_3_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/31")) return try g.route_shard_3.handle_ext_3_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/32")) return try g.route_shard_3.handle_ext_3_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/33")) return try g.route_shard_3.handle_ext_3_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/34")) return try g.route_shard_3.handle_ext_3_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/35")) return try g.route_shard_3.handle_ext_3_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/36")) return try g.route_shard_3.handle_ext_3_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/37")) return try g.route_shard_3.handle_ext_3_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/38")) return try g.route_shard_3.handle_ext_3_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/39")) return try g.route_shard_3.handle_ext_3_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/40")) return try g.route_shard_3.handle_ext_3_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/41")) return try g.route_shard_3.handle_ext_3_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/42")) return try g.route_shard_3.handle_ext_3_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/43")) return try g.route_shard_3.handle_ext_3_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/44")) return try g.route_shard_3.handle_ext_3_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/45")) return try g.route_shard_3.handle_ext_3_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/46")) return try g.route_shard_3.handle_ext_3_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/47")) return try g.route_shard_3.handle_ext_3_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/48")) return try g.route_shard_3.handle_ext_3_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/3/49")) return try g.route_shard_3.handle_ext_3_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/0")) return try g.route_shard_4.handle_ext_4_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/1")) return try g.route_shard_4.handle_ext_4_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/2")) return try g.route_shard_4.handle_ext_4_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/3")) return try g.route_shard_4.handle_ext_4_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/4")) return try g.route_shard_4.handle_ext_4_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/5")) return try g.route_shard_4.handle_ext_4_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/6")) return try g.route_shard_4.handle_ext_4_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/7")) return try g.route_shard_4.handle_ext_4_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/8")) return try g.route_shard_4.handle_ext_4_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/9")) return try g.route_shard_4.handle_ext_4_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/10")) return try g.route_shard_4.handle_ext_4_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/11")) return try g.route_shard_4.handle_ext_4_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/12")) return try g.route_shard_4.handle_ext_4_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/13")) return try g.route_shard_4.handle_ext_4_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/14")) return try g.route_shard_4.handle_ext_4_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/15")) return try g.route_shard_4.handle_ext_4_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/16")) return try g.route_shard_4.handle_ext_4_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/17")) return try g.route_shard_4.handle_ext_4_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/18")) return try g.route_shard_4.handle_ext_4_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/19")) return try g.route_shard_4.handle_ext_4_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/20")) return try g.route_shard_4.handle_ext_4_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/21")) return try g.route_shard_4.handle_ext_4_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/22")) return try g.route_shard_4.handle_ext_4_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/23")) return try g.route_shard_4.handle_ext_4_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/24")) return try g.route_shard_4.handle_ext_4_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/25")) return try g.route_shard_4.handle_ext_4_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/26")) return try g.route_shard_4.handle_ext_4_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/27")) return try g.route_shard_4.handle_ext_4_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/28")) return try g.route_shard_4.handle_ext_4_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/29")) return try g.route_shard_4.handle_ext_4_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/30")) return try g.route_shard_4.handle_ext_4_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/31")) return try g.route_shard_4.handle_ext_4_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/32")) return try g.route_shard_4.handle_ext_4_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/33")) return try g.route_shard_4.handle_ext_4_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/34")) return try g.route_shard_4.handle_ext_4_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/35")) return try g.route_shard_4.handle_ext_4_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/36")) return try g.route_shard_4.handle_ext_4_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/37")) return try g.route_shard_4.handle_ext_4_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/38")) return try g.route_shard_4.handle_ext_4_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/39")) return try g.route_shard_4.handle_ext_4_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/40")) return try g.route_shard_4.handle_ext_4_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/41")) return try g.route_shard_4.handle_ext_4_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/42")) return try g.route_shard_4.handle_ext_4_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/43")) return try g.route_shard_4.handle_ext_4_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/44")) return try g.route_shard_4.handle_ext_4_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/45")) return try g.route_shard_4.handle_ext_4_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/46")) return try g.route_shard_4.handle_ext_4_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/47")) return try g.route_shard_4.handle_ext_4_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/48")) return try g.route_shard_4.handle_ext_4_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/4/49")) return try g.route_shard_4.handle_ext_4_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/0")) return try g.route_shard_5.handle_ext_5_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/1")) return try g.route_shard_5.handle_ext_5_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/2")) return try g.route_shard_5.handle_ext_5_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/3")) return try g.route_shard_5.handle_ext_5_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/4")) return try g.route_shard_5.handle_ext_5_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/5")) return try g.route_shard_5.handle_ext_5_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/6")) return try g.route_shard_5.handle_ext_5_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/7")) return try g.route_shard_5.handle_ext_5_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/8")) return try g.route_shard_5.handle_ext_5_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/9")) return try g.route_shard_5.handle_ext_5_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/10")) return try g.route_shard_5.handle_ext_5_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/11")) return try g.route_shard_5.handle_ext_5_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/12")) return try g.route_shard_5.handle_ext_5_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/13")) return try g.route_shard_5.handle_ext_5_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/14")) return try g.route_shard_5.handle_ext_5_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/15")) return try g.route_shard_5.handle_ext_5_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/16")) return try g.route_shard_5.handle_ext_5_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/17")) return try g.route_shard_5.handle_ext_5_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/18")) return try g.route_shard_5.handle_ext_5_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/19")) return try g.route_shard_5.handle_ext_5_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/20")) return try g.route_shard_5.handle_ext_5_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/21")) return try g.route_shard_5.handle_ext_5_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/22")) return try g.route_shard_5.handle_ext_5_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/23")) return try g.route_shard_5.handle_ext_5_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/24")) return try g.route_shard_5.handle_ext_5_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/25")) return try g.route_shard_5.handle_ext_5_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/26")) return try g.route_shard_5.handle_ext_5_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/27")) return try g.route_shard_5.handle_ext_5_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/28")) return try g.route_shard_5.handle_ext_5_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/29")) return try g.route_shard_5.handle_ext_5_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/30")) return try g.route_shard_5.handle_ext_5_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/31")) return try g.route_shard_5.handle_ext_5_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/32")) return try g.route_shard_5.handle_ext_5_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/33")) return try g.route_shard_5.handle_ext_5_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/34")) return try g.route_shard_5.handle_ext_5_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/35")) return try g.route_shard_5.handle_ext_5_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/36")) return try g.route_shard_5.handle_ext_5_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/37")) return try g.route_shard_5.handle_ext_5_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/38")) return try g.route_shard_5.handle_ext_5_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/39")) return try g.route_shard_5.handle_ext_5_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/40")) return try g.route_shard_5.handle_ext_5_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/41")) return try g.route_shard_5.handle_ext_5_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/42")) return try g.route_shard_5.handle_ext_5_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/43")) return try g.route_shard_5.handle_ext_5_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/44")) return try g.route_shard_5.handle_ext_5_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/45")) return try g.route_shard_5.handle_ext_5_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/46")) return try g.route_shard_5.handle_ext_5_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/47")) return try g.route_shard_5.handle_ext_5_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/48")) return try g.route_shard_5.handle_ext_5_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/5/49")) return try g.route_shard_5.handle_ext_5_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/0")) return try g.route_shard_6.handle_ext_6_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/1")) return try g.route_shard_6.handle_ext_6_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/2")) return try g.route_shard_6.handle_ext_6_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/3")) return try g.route_shard_6.handle_ext_6_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/4")) return try g.route_shard_6.handle_ext_6_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/5")) return try g.route_shard_6.handle_ext_6_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/6")) return try g.route_shard_6.handle_ext_6_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/7")) return try g.route_shard_6.handle_ext_6_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/8")) return try g.route_shard_6.handle_ext_6_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/9")) return try g.route_shard_6.handle_ext_6_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/10")) return try g.route_shard_6.handle_ext_6_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/11")) return try g.route_shard_6.handle_ext_6_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/12")) return try g.route_shard_6.handle_ext_6_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/13")) return try g.route_shard_6.handle_ext_6_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/14")) return try g.route_shard_6.handle_ext_6_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/15")) return try g.route_shard_6.handle_ext_6_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/16")) return try g.route_shard_6.handle_ext_6_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/17")) return try g.route_shard_6.handle_ext_6_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/18")) return try g.route_shard_6.handle_ext_6_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/19")) return try g.route_shard_6.handle_ext_6_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/20")) return try g.route_shard_6.handle_ext_6_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/21")) return try g.route_shard_6.handle_ext_6_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/22")) return try g.route_shard_6.handle_ext_6_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/23")) return try g.route_shard_6.handle_ext_6_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/24")) return try g.route_shard_6.handle_ext_6_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/25")) return try g.route_shard_6.handle_ext_6_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/26")) return try g.route_shard_6.handle_ext_6_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/27")) return try g.route_shard_6.handle_ext_6_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/28")) return try g.route_shard_6.handle_ext_6_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/29")) return try g.route_shard_6.handle_ext_6_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/30")) return try g.route_shard_6.handle_ext_6_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/31")) return try g.route_shard_6.handle_ext_6_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/32")) return try g.route_shard_6.handle_ext_6_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/33")) return try g.route_shard_6.handle_ext_6_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/34")) return try g.route_shard_6.handle_ext_6_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/35")) return try g.route_shard_6.handle_ext_6_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/36")) return try g.route_shard_6.handle_ext_6_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/37")) return try g.route_shard_6.handle_ext_6_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/38")) return try g.route_shard_6.handle_ext_6_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/39")) return try g.route_shard_6.handle_ext_6_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/40")) return try g.route_shard_6.handle_ext_6_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/41")) return try g.route_shard_6.handle_ext_6_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/42")) return try g.route_shard_6.handle_ext_6_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/43")) return try g.route_shard_6.handle_ext_6_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/44")) return try g.route_shard_6.handle_ext_6_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/45")) return try g.route_shard_6.handle_ext_6_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/46")) return try g.route_shard_6.handle_ext_6_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/47")) return try g.route_shard_6.handle_ext_6_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/48")) return try g.route_shard_6.handle_ext_6_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/6/49")) return try g.route_shard_6.handle_ext_6_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/0")) return try g.route_shard_7.handle_ext_7_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/1")) return try g.route_shard_7.handle_ext_7_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/2")) return try g.route_shard_7.handle_ext_7_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/3")) return try g.route_shard_7.handle_ext_7_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/4")) return try g.route_shard_7.handle_ext_7_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/5")) return try g.route_shard_7.handle_ext_7_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/6")) return try g.route_shard_7.handle_ext_7_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/7")) return try g.route_shard_7.handle_ext_7_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/8")) return try g.route_shard_7.handle_ext_7_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/9")) return try g.route_shard_7.handle_ext_7_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/10")) return try g.route_shard_7.handle_ext_7_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/11")) return try g.route_shard_7.handle_ext_7_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/12")) return try g.route_shard_7.handle_ext_7_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/13")) return try g.route_shard_7.handle_ext_7_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/14")) return try g.route_shard_7.handle_ext_7_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/15")) return try g.route_shard_7.handle_ext_7_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/16")) return try g.route_shard_7.handle_ext_7_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/17")) return try g.route_shard_7.handle_ext_7_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/18")) return try g.route_shard_7.handle_ext_7_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/19")) return try g.route_shard_7.handle_ext_7_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/20")) return try g.route_shard_7.handle_ext_7_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/21")) return try g.route_shard_7.handle_ext_7_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/22")) return try g.route_shard_7.handle_ext_7_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/23")) return try g.route_shard_7.handle_ext_7_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/24")) return try g.route_shard_7.handle_ext_7_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/25")) return try g.route_shard_7.handle_ext_7_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/26")) return try g.route_shard_7.handle_ext_7_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/27")) return try g.route_shard_7.handle_ext_7_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/28")) return try g.route_shard_7.handle_ext_7_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/29")) return try g.route_shard_7.handle_ext_7_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/30")) return try g.route_shard_7.handle_ext_7_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/31")) return try g.route_shard_7.handle_ext_7_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/32")) return try g.route_shard_7.handle_ext_7_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/33")) return try g.route_shard_7.handle_ext_7_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/34")) return try g.route_shard_7.handle_ext_7_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/35")) return try g.route_shard_7.handle_ext_7_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/36")) return try g.route_shard_7.handle_ext_7_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/37")) return try g.route_shard_7.handle_ext_7_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/38")) return try g.route_shard_7.handle_ext_7_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/39")) return try g.route_shard_7.handle_ext_7_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/40")) return try g.route_shard_7.handle_ext_7_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/41")) return try g.route_shard_7.handle_ext_7_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/42")) return try g.route_shard_7.handle_ext_7_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/43")) return try g.route_shard_7.handle_ext_7_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/44")) return try g.route_shard_7.handle_ext_7_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/45")) return try g.route_shard_7.handle_ext_7_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/46")) return try g.route_shard_7.handle_ext_7_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/47")) return try g.route_shard_7.handle_ext_7_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/48")) return try g.route_shard_7.handle_ext_7_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/7/49")) return try g.route_shard_7.handle_ext_7_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/0")) return try g.route_shard_8.handle_ext_8_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/1")) return try g.route_shard_8.handle_ext_8_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/2")) return try g.route_shard_8.handle_ext_8_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/3")) return try g.route_shard_8.handle_ext_8_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/4")) return try g.route_shard_8.handle_ext_8_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/5")) return try g.route_shard_8.handle_ext_8_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/6")) return try g.route_shard_8.handle_ext_8_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/7")) return try g.route_shard_8.handle_ext_8_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/8")) return try g.route_shard_8.handle_ext_8_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/9")) return try g.route_shard_8.handle_ext_8_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/10")) return try g.route_shard_8.handle_ext_8_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/11")) return try g.route_shard_8.handle_ext_8_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/12")) return try g.route_shard_8.handle_ext_8_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/13")) return try g.route_shard_8.handle_ext_8_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/14")) return try g.route_shard_8.handle_ext_8_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/15")) return try g.route_shard_8.handle_ext_8_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/16")) return try g.route_shard_8.handle_ext_8_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/17")) return try g.route_shard_8.handle_ext_8_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/18")) return try g.route_shard_8.handle_ext_8_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/19")) return try g.route_shard_8.handle_ext_8_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/20")) return try g.route_shard_8.handle_ext_8_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/21")) return try g.route_shard_8.handle_ext_8_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/22")) return try g.route_shard_8.handle_ext_8_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/23")) return try g.route_shard_8.handle_ext_8_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/24")) return try g.route_shard_8.handle_ext_8_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/25")) return try g.route_shard_8.handle_ext_8_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/26")) return try g.route_shard_8.handle_ext_8_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/27")) return try g.route_shard_8.handle_ext_8_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/28")) return try g.route_shard_8.handle_ext_8_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/29")) return try g.route_shard_8.handle_ext_8_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/30")) return try g.route_shard_8.handle_ext_8_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/31")) return try g.route_shard_8.handle_ext_8_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/32")) return try g.route_shard_8.handle_ext_8_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/33")) return try g.route_shard_8.handle_ext_8_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/34")) return try g.route_shard_8.handle_ext_8_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/35")) return try g.route_shard_8.handle_ext_8_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/36")) return try g.route_shard_8.handle_ext_8_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/37")) return try g.route_shard_8.handle_ext_8_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/38")) return try g.route_shard_8.handle_ext_8_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/39")) return try g.route_shard_8.handle_ext_8_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/40")) return try g.route_shard_8.handle_ext_8_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/41")) return try g.route_shard_8.handle_ext_8_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/42")) return try g.route_shard_8.handle_ext_8_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/43")) return try g.route_shard_8.handle_ext_8_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/44")) return try g.route_shard_8.handle_ext_8_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/45")) return try g.route_shard_8.handle_ext_8_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/46")) return try g.route_shard_8.handle_ext_8_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/47")) return try g.route_shard_8.handle_ext_8_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/48")) return try g.route_shard_8.handle_ext_8_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/8/49")) return try g.route_shard_8.handle_ext_8_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/0")) return try g.route_shard_9.handle_ext_9_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/1")) return try g.route_shard_9.handle_ext_9_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/2")) return try g.route_shard_9.handle_ext_9_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/3")) return try g.route_shard_9.handle_ext_9_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/4")) return try g.route_shard_9.handle_ext_9_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/5")) return try g.route_shard_9.handle_ext_9_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/6")) return try g.route_shard_9.handle_ext_9_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/7")) return try g.route_shard_9.handle_ext_9_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/8")) return try g.route_shard_9.handle_ext_9_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/9")) return try g.route_shard_9.handle_ext_9_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/10")) return try g.route_shard_9.handle_ext_9_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/11")) return try g.route_shard_9.handle_ext_9_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/12")) return try g.route_shard_9.handle_ext_9_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/13")) return try g.route_shard_9.handle_ext_9_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/14")) return try g.route_shard_9.handle_ext_9_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/15")) return try g.route_shard_9.handle_ext_9_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/16")) return try g.route_shard_9.handle_ext_9_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/17")) return try g.route_shard_9.handle_ext_9_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/18")) return try g.route_shard_9.handle_ext_9_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/19")) return try g.route_shard_9.handle_ext_9_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/20")) return try g.route_shard_9.handle_ext_9_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/21")) return try g.route_shard_9.handle_ext_9_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/22")) return try g.route_shard_9.handle_ext_9_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/23")) return try g.route_shard_9.handle_ext_9_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/24")) return try g.route_shard_9.handle_ext_9_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/25")) return try g.route_shard_9.handle_ext_9_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/26")) return try g.route_shard_9.handle_ext_9_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/27")) return try g.route_shard_9.handle_ext_9_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/28")) return try g.route_shard_9.handle_ext_9_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/29")) return try g.route_shard_9.handle_ext_9_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/30")) return try g.route_shard_9.handle_ext_9_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/31")) return try g.route_shard_9.handle_ext_9_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/32")) return try g.route_shard_9.handle_ext_9_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/33")) return try g.route_shard_9.handle_ext_9_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/34")) return try g.route_shard_9.handle_ext_9_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/35")) return try g.route_shard_9.handle_ext_9_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/36")) return try g.route_shard_9.handle_ext_9_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/37")) return try g.route_shard_9.handle_ext_9_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/38")) return try g.route_shard_9.handle_ext_9_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/39")) return try g.route_shard_9.handle_ext_9_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/40")) return try g.route_shard_9.handle_ext_9_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/41")) return try g.route_shard_9.handle_ext_9_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/42")) return try g.route_shard_9.handle_ext_9_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/43")) return try g.route_shard_9.handle_ext_9_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/44")) return try g.route_shard_9.handle_ext_9_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/45")) return try g.route_shard_9.handle_ext_9_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/46")) return try g.route_shard_9.handle_ext_9_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/47")) return try g.route_shard_9.handle_ext_9_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/48")) return try g.route_shard_9.handle_ext_9_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/9/49")) return try g.route_shard_9.handle_ext_9_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/0")) return try g.route_shard_10.handle_ext_10_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/1")) return try g.route_shard_10.handle_ext_10_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/2")) return try g.route_shard_10.handle_ext_10_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/3")) return try g.route_shard_10.handle_ext_10_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/4")) return try g.route_shard_10.handle_ext_10_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/5")) return try g.route_shard_10.handle_ext_10_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/6")) return try g.route_shard_10.handle_ext_10_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/7")) return try g.route_shard_10.handle_ext_10_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/8")) return try g.route_shard_10.handle_ext_10_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/9")) return try g.route_shard_10.handle_ext_10_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/10")) return try g.route_shard_10.handle_ext_10_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/11")) return try g.route_shard_10.handle_ext_10_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/12")) return try g.route_shard_10.handle_ext_10_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/13")) return try g.route_shard_10.handle_ext_10_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/14")) return try g.route_shard_10.handle_ext_10_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/15")) return try g.route_shard_10.handle_ext_10_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/16")) return try g.route_shard_10.handle_ext_10_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/17")) return try g.route_shard_10.handle_ext_10_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/18")) return try g.route_shard_10.handle_ext_10_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/19")) return try g.route_shard_10.handle_ext_10_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/20")) return try g.route_shard_10.handle_ext_10_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/21")) return try g.route_shard_10.handle_ext_10_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/22")) return try g.route_shard_10.handle_ext_10_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/23")) return try g.route_shard_10.handle_ext_10_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/24")) return try g.route_shard_10.handle_ext_10_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/25")) return try g.route_shard_10.handle_ext_10_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/26")) return try g.route_shard_10.handle_ext_10_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/27")) return try g.route_shard_10.handle_ext_10_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/28")) return try g.route_shard_10.handle_ext_10_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/29")) return try g.route_shard_10.handle_ext_10_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/30")) return try g.route_shard_10.handle_ext_10_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/31")) return try g.route_shard_10.handle_ext_10_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/32")) return try g.route_shard_10.handle_ext_10_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/33")) return try g.route_shard_10.handle_ext_10_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/34")) return try g.route_shard_10.handle_ext_10_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/35")) return try g.route_shard_10.handle_ext_10_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/36")) return try g.route_shard_10.handle_ext_10_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/37")) return try g.route_shard_10.handle_ext_10_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/38")) return try g.route_shard_10.handle_ext_10_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/39")) return try g.route_shard_10.handle_ext_10_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/40")) return try g.route_shard_10.handle_ext_10_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/41")) return try g.route_shard_10.handle_ext_10_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/42")) return try g.route_shard_10.handle_ext_10_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/43")) return try g.route_shard_10.handle_ext_10_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/44")) return try g.route_shard_10.handle_ext_10_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/45")) return try g.route_shard_10.handle_ext_10_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/46")) return try g.route_shard_10.handle_ext_10_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/47")) return try g.route_shard_10.handle_ext_10_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/48")) return try g.route_shard_10.handle_ext_10_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/10/49")) return try g.route_shard_10.handle_ext_10_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/0")) return try g.route_shard_11.handle_ext_11_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/1")) return try g.route_shard_11.handle_ext_11_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/2")) return try g.route_shard_11.handle_ext_11_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/3")) return try g.route_shard_11.handle_ext_11_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/4")) return try g.route_shard_11.handle_ext_11_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/5")) return try g.route_shard_11.handle_ext_11_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/6")) return try g.route_shard_11.handle_ext_11_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/7")) return try g.route_shard_11.handle_ext_11_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/8")) return try g.route_shard_11.handle_ext_11_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/9")) return try g.route_shard_11.handle_ext_11_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/10")) return try g.route_shard_11.handle_ext_11_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/11")) return try g.route_shard_11.handle_ext_11_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/12")) return try g.route_shard_11.handle_ext_11_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/13")) return try g.route_shard_11.handle_ext_11_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/14")) return try g.route_shard_11.handle_ext_11_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/15")) return try g.route_shard_11.handle_ext_11_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/16")) return try g.route_shard_11.handle_ext_11_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/17")) return try g.route_shard_11.handle_ext_11_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/18")) return try g.route_shard_11.handle_ext_11_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/19")) return try g.route_shard_11.handle_ext_11_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/20")) return try g.route_shard_11.handle_ext_11_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/21")) return try g.route_shard_11.handle_ext_11_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/22")) return try g.route_shard_11.handle_ext_11_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/23")) return try g.route_shard_11.handle_ext_11_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/24")) return try g.route_shard_11.handle_ext_11_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/25")) return try g.route_shard_11.handle_ext_11_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/26")) return try g.route_shard_11.handle_ext_11_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/27")) return try g.route_shard_11.handle_ext_11_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/28")) return try g.route_shard_11.handle_ext_11_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/29")) return try g.route_shard_11.handle_ext_11_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/30")) return try g.route_shard_11.handle_ext_11_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/31")) return try g.route_shard_11.handle_ext_11_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/32")) return try g.route_shard_11.handle_ext_11_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/33")) return try g.route_shard_11.handle_ext_11_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/34")) return try g.route_shard_11.handle_ext_11_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/35")) return try g.route_shard_11.handle_ext_11_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/36")) return try g.route_shard_11.handle_ext_11_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/37")) return try g.route_shard_11.handle_ext_11_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/38")) return try g.route_shard_11.handle_ext_11_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/39")) return try g.route_shard_11.handle_ext_11_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/40")) return try g.route_shard_11.handle_ext_11_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/41")) return try g.route_shard_11.handle_ext_11_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/42")) return try g.route_shard_11.handle_ext_11_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/43")) return try g.route_shard_11.handle_ext_11_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/44")) return try g.route_shard_11.handle_ext_11_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/45")) return try g.route_shard_11.handle_ext_11_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/46")) return try g.route_shard_11.handle_ext_11_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/47")) return try g.route_shard_11.handle_ext_11_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/48")) return try g.route_shard_11.handle_ext_11_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/11/49")) return try g.route_shard_11.handle_ext_11_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/0")) return try g.route_shard_12.handle_ext_12_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/1")) return try g.route_shard_12.handle_ext_12_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/2")) return try g.route_shard_12.handle_ext_12_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/3")) return try g.route_shard_12.handle_ext_12_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/4")) return try g.route_shard_12.handle_ext_12_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/5")) return try g.route_shard_12.handle_ext_12_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/6")) return try g.route_shard_12.handle_ext_12_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/7")) return try g.route_shard_12.handle_ext_12_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/8")) return try g.route_shard_12.handle_ext_12_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/9")) return try g.route_shard_12.handle_ext_12_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/10")) return try g.route_shard_12.handle_ext_12_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/11")) return try g.route_shard_12.handle_ext_12_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/12")) return try g.route_shard_12.handle_ext_12_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/13")) return try g.route_shard_12.handle_ext_12_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/14")) return try g.route_shard_12.handle_ext_12_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/15")) return try g.route_shard_12.handle_ext_12_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/16")) return try g.route_shard_12.handle_ext_12_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/17")) return try g.route_shard_12.handle_ext_12_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/18")) return try g.route_shard_12.handle_ext_12_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/19")) return try g.route_shard_12.handle_ext_12_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/20")) return try g.route_shard_12.handle_ext_12_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/21")) return try g.route_shard_12.handle_ext_12_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/22")) return try g.route_shard_12.handle_ext_12_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/23")) return try g.route_shard_12.handle_ext_12_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/24")) return try g.route_shard_12.handle_ext_12_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/25")) return try g.route_shard_12.handle_ext_12_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/26")) return try g.route_shard_12.handle_ext_12_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/27")) return try g.route_shard_12.handle_ext_12_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/28")) return try g.route_shard_12.handle_ext_12_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/29")) return try g.route_shard_12.handle_ext_12_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/30")) return try g.route_shard_12.handle_ext_12_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/31")) return try g.route_shard_12.handle_ext_12_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/32")) return try g.route_shard_12.handle_ext_12_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/33")) return try g.route_shard_12.handle_ext_12_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/34")) return try g.route_shard_12.handle_ext_12_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/35")) return try g.route_shard_12.handle_ext_12_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/36")) return try g.route_shard_12.handle_ext_12_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/37")) return try g.route_shard_12.handle_ext_12_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/38")) return try g.route_shard_12.handle_ext_12_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/39")) return try g.route_shard_12.handle_ext_12_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/40")) return try g.route_shard_12.handle_ext_12_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/41")) return try g.route_shard_12.handle_ext_12_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/42")) return try g.route_shard_12.handle_ext_12_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/43")) return try g.route_shard_12.handle_ext_12_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/44")) return try g.route_shard_12.handle_ext_12_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/45")) return try g.route_shard_12.handle_ext_12_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/46")) return try g.route_shard_12.handle_ext_12_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/47")) return try g.route_shard_12.handle_ext_12_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/48")) return try g.route_shard_12.handle_ext_12_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/12/49")) return try g.route_shard_12.handle_ext_12_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/0")) return try g.route_shard_13.handle_ext_13_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/1")) return try g.route_shard_13.handle_ext_13_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/2")) return try g.route_shard_13.handle_ext_13_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/3")) return try g.route_shard_13.handle_ext_13_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/4")) return try g.route_shard_13.handle_ext_13_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/5")) return try g.route_shard_13.handle_ext_13_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/6")) return try g.route_shard_13.handle_ext_13_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/7")) return try g.route_shard_13.handle_ext_13_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/8")) return try g.route_shard_13.handle_ext_13_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/9")) return try g.route_shard_13.handle_ext_13_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/10")) return try g.route_shard_13.handle_ext_13_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/11")) return try g.route_shard_13.handle_ext_13_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/12")) return try g.route_shard_13.handle_ext_13_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/13")) return try g.route_shard_13.handle_ext_13_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/14")) return try g.route_shard_13.handle_ext_13_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/15")) return try g.route_shard_13.handle_ext_13_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/16")) return try g.route_shard_13.handle_ext_13_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/17")) return try g.route_shard_13.handle_ext_13_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/18")) return try g.route_shard_13.handle_ext_13_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/19")) return try g.route_shard_13.handle_ext_13_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/20")) return try g.route_shard_13.handle_ext_13_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/21")) return try g.route_shard_13.handle_ext_13_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/22")) return try g.route_shard_13.handle_ext_13_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/23")) return try g.route_shard_13.handle_ext_13_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/24")) return try g.route_shard_13.handle_ext_13_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/25")) return try g.route_shard_13.handle_ext_13_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/26")) return try g.route_shard_13.handle_ext_13_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/27")) return try g.route_shard_13.handle_ext_13_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/28")) return try g.route_shard_13.handle_ext_13_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/29")) return try g.route_shard_13.handle_ext_13_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/30")) return try g.route_shard_13.handle_ext_13_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/31")) return try g.route_shard_13.handle_ext_13_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/32")) return try g.route_shard_13.handle_ext_13_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/33")) return try g.route_shard_13.handle_ext_13_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/34")) return try g.route_shard_13.handle_ext_13_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/35")) return try g.route_shard_13.handle_ext_13_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/36")) return try g.route_shard_13.handle_ext_13_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/37")) return try g.route_shard_13.handle_ext_13_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/38")) return try g.route_shard_13.handle_ext_13_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/39")) return try g.route_shard_13.handle_ext_13_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/40")) return try g.route_shard_13.handle_ext_13_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/41")) return try g.route_shard_13.handle_ext_13_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/42")) return try g.route_shard_13.handle_ext_13_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/43")) return try g.route_shard_13.handle_ext_13_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/44")) return try g.route_shard_13.handle_ext_13_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/45")) return try g.route_shard_13.handle_ext_13_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/46")) return try g.route_shard_13.handle_ext_13_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/47")) return try g.route_shard_13.handle_ext_13_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/48")) return try g.route_shard_13.handle_ext_13_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/13/49")) return try g.route_shard_13.handle_ext_13_49(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/0")) return try g.route_shard_14.handle_ext_14_0(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/1")) return try g.route_shard_14.handle_ext_14_1(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/2")) return try g.route_shard_14.handle_ext_14_2(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/3")) return try g.route_shard_14.handle_ext_14_3(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/4")) return try g.route_shard_14.handle_ext_14_4(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/5")) return try g.route_shard_14.handle_ext_14_5(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/6")) return try g.route_shard_14.handle_ext_14_6(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/7")) return try g.route_shard_14.handle_ext_14_7(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/8")) return try g.route_shard_14.handle_ext_14_8(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/9")) return try g.route_shard_14.handle_ext_14_9(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/10")) return try g.route_shard_14.handle_ext_14_10(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/11")) return try g.route_shard_14.handle_ext_14_11(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/12")) return try g.route_shard_14.handle_ext_14_12(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/13")) return try g.route_shard_14.handle_ext_14_13(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/14")) return try g.route_shard_14.handle_ext_14_14(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/15")) return try g.route_shard_14.handle_ext_14_15(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/16")) return try g.route_shard_14.handle_ext_14_16(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/17")) return try g.route_shard_14.handle_ext_14_17(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/18")) return try g.route_shard_14.handle_ext_14_18(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/19")) return try g.route_shard_14.handle_ext_14_19(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/20")) return try g.route_shard_14.handle_ext_14_20(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/21")) return try g.route_shard_14.handle_ext_14_21(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/22")) return try g.route_shard_14.handle_ext_14_22(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/23")) return try g.route_shard_14.handle_ext_14_23(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/24")) return try g.route_shard_14.handle_ext_14_24(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/25")) return try g.route_shard_14.handle_ext_14_25(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/26")) return try g.route_shard_14.handle_ext_14_26(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/27")) return try g.route_shard_14.handle_ext_14_27(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/28")) return try g.route_shard_14.handle_ext_14_28(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/29")) return try g.route_shard_14.handle_ext_14_29(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/30")) return try g.route_shard_14.handle_ext_14_30(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/31")) return try g.route_shard_14.handle_ext_14_31(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/32")) return try g.route_shard_14.handle_ext_14_32(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/33")) return try g.route_shard_14.handle_ext_14_33(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/34")) return try g.route_shard_14.handle_ext_14_34(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/35")) return try g.route_shard_14.handle_ext_14_35(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/36")) return try g.route_shard_14.handle_ext_14_36(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/37")) return try g.route_shard_14.handle_ext_14_37(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/38")) return try g.route_shard_14.handle_ext_14_38(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/39")) return try g.route_shard_14.handle_ext_14_39(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/40")) return try g.route_shard_14.handle_ext_14_40(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/41")) return try g.route_shard_14.handle_ext_14_41(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/42")) return try g.route_shard_14.handle_ext_14_42(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/43")) return try g.route_shard_14.handle_ext_14_43(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/44")) return try g.route_shard_14.handle_ext_14_44(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/45")) return try g.route_shard_14.handle_ext_14_45(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/46")) return try g.route_shard_14.handle_ext_14_46(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/47")) return try g.route_shard_14.handle_ext_14_47(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/48")) return try g.route_shard_14.handle_ext_14_48(gpa, body);
    if (std.mem.eql(u8, path, "/ext/14/49")) return try g.route_shard_14.handle_ext_14_49(gpa, body);
    return null;
}

pub fn listAllRoutesJson(gpa: std.mem.Allocator) ![]u8 {
    var aw: std.Io.Writer.Allocating = .init(gpa);
    errdefer aw.deinit();
    try aw.writer.writeAll("{\"routes\":[");
    var first = true;
    for (g.route_shard_0.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":0}");
    }
    for (g.route_shard_1.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":1}");
    }
    for (g.route_shard_2.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":2}");
    }
    for (g.route_shard_3.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":3}");
    }
    for (g.route_shard_4.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":4}");
    }
    for (g.route_shard_5.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":5}");
    }
    for (g.route_shard_6.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":6}");
    }
    for (g.route_shard_7.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":7}");
    }
    for (g.route_shard_8.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":8}");
    }
    for (g.route_shard_9.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":9}");
    }
    for (g.route_shard_10.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":10}");
    }
    for (g.route_shard_11.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":11}");
    }
    for (g.route_shard_12.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":12}");
    }
    for (g.route_shard_13.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":13}");
    }
    for (g.route_shard_14.routes) |r| {
        if (!first) try aw.writer.writeAll(",");
        first = false;
        try aw.writer.writeAll("{\"method\":");
        try std.json.Stringify.value(r.method, .{}, &aw.writer);
        try aw.writer.writeAll(",\"path\":");
        try std.json.Stringify.value(r.path, .{}, &aw.writer);
        try aw.writer.writeAll(",\"name\":");
        try std.json.Stringify.value(r.name, .{}, &aw.writer);
        try aw.writer.writeAll(",\"shard\":14}");
    }
    try aw.writer.writeAll("]}");
    return try aw.toOwnedSlice();
}

pub fn routeCount() usize {
    var n: usize = 0;
    n += g.route_shard_0.routes.len;
    n += g.route_shard_1.routes.len;
    n += g.route_shard_2.routes.len;
    n += g.route_shard_3.routes.len;
    n += g.route_shard_4.routes.len;
    n += g.route_shard_5.routes.len;
    n += g.route_shard_6.routes.len;
    n += g.route_shard_7.routes.len;
    n += g.route_shard_8.routes.len;
    n += g.route_shard_9.routes.len;
    n += g.route_shard_10.routes.len;
    n += g.route_shard_11.routes.len;
    n += g.route_shard_12.routes.len;
    n += g.route_shard_13.routes.len;
    n += g.route_shard_14.routes.len;
    return n;
}

test "all route shards matchable" {
    try std.testing.expect(matchRoute("GET", "/health") != null);
    try std.testing.expect(matchRoute("POST", "/ext/5/3") != null);
    try std.testing.expect(matchRoute("POST", "/ext/14/49") != null);
    try std.testing.expect(routeCount() > 100);
    const gpa = std.testing.allocator;
    const h = try handleExt(gpa, "/ext/5/3", "{}");
    try std.testing.expect(h != null);
    defer gpa.free(h.?);
    try std.testing.expect(std.mem.indexOf(u8, h.?, "ext_5_3") != null);
}
