//! Source Editor method names and JavaScript arities.
pub const Method = enum(c_int) {
    validPasteIds,
    segment,
    getPaddingX,
    setPaddingX,
    getAutocompleteMaxVisible,
    setAutocompleteMaxVisible,
    setAutocompleteProvider,
    addToHistory,
    isEditorEmpty,
    isOnFirstVisualLine,
    isOnLastVisualLine,
    navigateHistory,
    exitHistoryBrowsing,
    setTextInternal,
    invalidate,
    renderTopBorder,
    renderBottomBorder,
    render,
    handleMouse,
    handleInput,
    layoutText,
    getText,
    expandPasteMarkers,
    getExpandedText,
    getLines,
    getCursor,
    setText,
    insertTextAtCursor,
    normalizeText,
    insertTextAtCursorInternal,
    insertCharacter,
    handlePaste,
    addNewLine,
    shouldSubmitOnBackslashEnter,
    submitValue,
    handleBackspace,
    setCursorCol,
    moveToVisualLine,
    computeVerticalMoveColumn,
    moveToLineStart,
    moveToLineEnd,
    deleteToStartOfLine,
    deleteToEndOfLine,
    deleteWordBackwards,
    deleteWordForward,
    handleForwardDelete,
    buildVisualLineMap,
    findVisualLineAt,
    findCurrentVisualLine,
    moveCursor,
    pageScroll,
    moveWordBackwards,
    yank,
    yankPop,
    insertYankedText,
    deleteYankedText,
    pushUndoSnapshot,
    undo,
    jumpToChar,
    moveWordForwards,
    isSlashMenuAllowed,
    isAtStartOfMessage,
    isInSlashCommandContext,
    getBestAutocompleteMatchIndex,
    createAutocompleteList,
    tryTriggerAutocomplete,
    handleTabCompletion,
    handleSlashCommandCompletion,
    forceFileAutocomplete,
    requestAutocomplete,
    startAutocompleteRequest,
    setAutocompleteTriggerCharacters,
    getAutocompleteDebounceMs,
    runAutocompleteRequest,
    isAutocompleteRequestCurrent,
    applyAutocompleteSuggestions,
    cancelAutocompleteRequest,
    clearAutocompleteUi,
    cancelAutocomplete,
    isShowingAutocomplete,
    updateAutocomplete,
};
pub fn arity(method: Method) c_int {
    return switch (method) {
        .validPasteIds => 0,
        .segment => 2,
        .getPaddingX => 0,
        .setPaddingX => 1,
        .getAutocompleteMaxVisible => 0,
        .setAutocompleteMaxVisible => 1,
        .setAutocompleteProvider => 1,
        .addToHistory => 1,
        .isEditorEmpty => 0,
        .isOnFirstVisualLine => 0,
        .isOnLastVisualLine => 0,
        .navigateHistory => 1,
        .exitHistoryBrowsing => 0,
        .setTextInternal => 1,
        .invalidate => 0,
        .renderTopBorder => 2,
        .renderBottomBorder => 2,
        .render => 1,
        .handleMouse => 1,
        .handleInput => 1,
        .layoutText => 1,
        .getText => 0,
        .expandPasteMarkers => 1,
        .getExpandedText => 0,
        .getLines => 0,
        .getCursor => 0,
        .setText => 1,
        .insertTextAtCursor => 1,
        .normalizeText => 1,
        .insertTextAtCursorInternal => 1,
        .insertCharacter => 2,
        .handlePaste => 1,
        .addNewLine => 0,
        .shouldSubmitOnBackslashEnter => 2,
        .submitValue => 0,
        .handleBackspace => 0,
        .setCursorCol => 1,
        .moveToVisualLine => 3,
        .computeVerticalMoveColumn => 3,
        .moveToLineStart => 0,
        .moveToLineEnd => 0,
        .deleteToStartOfLine => 0,
        .deleteToEndOfLine => 0,
        .deleteWordBackwards => 0,
        .deleteWordForward => 0,
        .handleForwardDelete => 0,
        .buildVisualLineMap => 1,
        .findVisualLineAt => 3,
        .findCurrentVisualLine => 1,
        .moveCursor => 2,
        .pageScroll => 1,
        .moveWordBackwards => 0,
        .yank => 0,
        .yankPop => 0,
        .insertYankedText => 1,
        .deleteYankedText => 0,
        .pushUndoSnapshot => 0,
        .undo => 0,
        .jumpToChar => 2,
        .moveWordForwards => 0,
        .isSlashMenuAllowed => 0,
        .isAtStartOfMessage => 0,
        .isInSlashCommandContext => 1,
        .getBestAutocompleteMatchIndex => 2,
        .createAutocompleteList => 2,
        .tryTriggerAutocomplete => 0,
        .handleTabCompletion => 0,
        .handleSlashCommandCompletion => 0,
        .forceFileAutocomplete => 0,
        .requestAutocomplete => 1,
        .startAutocompleteRequest => 2,
        .setAutocompleteTriggerCharacters => 1,
        .getAutocompleteDebounceMs => 1,
        .runAutocompleteRequest => 6,
        .isAutocompleteRequestCurrent => 5,
        .applyAutocompleteSuggestions => 2,
        .cancelAutocompleteRequest => 0,
        .clearAutocompleteUi => 0,
        .cancelAutocomplete => 0,
        .isShowingAutocomplete => 0,
        .updateAutocomplete => 0,
    };
}
