//! Extract pinned TypeBox regex data without evaluating source JavaScript.
const std = @import("std");
const File = struct { path: []const u8, bytes: []const u8, sha256: [64]u8 };
fn less(_: void, a: File, b: File) bool {
    return std.mem.lessThan(u8, a.path, b.path);
}
fn quote(writer: *std.Io.Writer, value: []const u8) !void {
    try writer.writeByte('"');
    for (value) |byte| switch (byte) {
        '"' => try writer.writeAll("\\\""),
        '\\' => try writer.writeAll("\\\\"),
        '\n' => try writer.writeAll("\\n"),
        '\r' => try writer.writeAll("\\r"),
        '\t' => try writer.writeAll("\\t"),
        0...8, 11...12, 14...31 => try writer.print("\\x{x:0>2}", .{byte}),
        else => try writer.writeByte(byte),
    };
    try writer.writeByte('"');
}
fn render(gpa: std.mem.Allocator, files: []const File) ![]u8 {
    var output: std.Io.Writer.Allocating = .init(gpa);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("// Generated by tools/typebox_format_patterns.zig; TypeBox 1.3.27 (MIT).\n// Native regex data only. No JavaScript source is evaluated or shipped.\n");
    try writer.writeAll("pub const Source = struct { path: []const u8, sha256: []const u8 };\npub const sources = [_]Source{\n");
    for (files) |file| {
        try writer.writeAll("    .{ .path = ");
        try quote(writer, file.path);
        try writer.writeAll(", .sha256 = ");
        try quote(writer, &file.sha256);
        try writer.writeAll(" },\n");
    }
    try writer.writeAll("};\npub const Pattern = struct { file: []const u8, binding: []const u8, expression: []const u8, flags: []const u8 };\npub const patterns = [_]Pattern{\n");
    var count: usize = 0;
    for (files) |file| {
        var lines = std.mem.splitScalar(u8, file.bytes, '\n');
        while (lines.next()) |raw_line| {
            const line = std.mem.trim(u8, raw_line, " \t\r");
            const declaration = if (std.mem.startsWith(u8, line, "export const ")) line[13..] else if (std.mem.startsWith(u8, line, "const ")) line[6..] else continue;
            const marker = std.mem.indexOf(u8, declaration, " = /") orelse continue;
            const binding = declaration[0..marker];
            for (binding) |byte| if (!std.ascii.isAlphanumeric(byte) and byte != '_') return error.InvalidBinding;
            const start = marker + 4;
            var index = start;
            var escaped = false;
            var in_class = false;
            while (index < declaration.len) : (index += 1) {
                const byte = declaration[index];
                if (escaped) {
                    escaped = false;
                    continue;
                }
                if (byte == '\\') {
                    escaped = true;
                    continue;
                }
                if (byte == '[') in_class = true else if (byte == ']') in_class = false else if (byte == '/' and !in_class) break;
            }
            if (index == declaration.len) return error.UnterminatedRegex;
            const end = index;
            index += 1;
            const flags_start = index;
            while (index < declaration.len and std.ascii.isAlphabetic(declaration[index])) : (index += 1) {}
            const flags = declaration[flags_start..index];
            if (index >= declaration.len or declaration[index] != ';') return error.UnsupportedRegexDeclaration;
            try writer.writeAll("    .{ .file = ");
            try quote(writer, file.path);
            try writer.writeAll(", .binding = ");
            try quote(writer, binding);
            try writer.writeAll(", .expression = ");
            try quote(writer, declaration[start..end]);
            try writer.writeAll(", .flags = ");
            try quote(writer, flags);
            try writer.writeAll(" },\n");
            count += 1;
        }
    }
    if (count == 0) return error.NoRegexPatterns;
    try writer.writeAll("};\n");
    return gpa.dupe(u8, output.written());
}
pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len < 3 or args.len > 4) return error.ExpectedPackageRootAndOutput;
    const check = args.len == 4 and std.mem.eql(u8, args[3], "--check");
    if (args.len == 4 and !check) return error.InvalidOption;
    const package_path = try std.fs.path.join(init.gpa, &.{ args[1], "package.json" });
    defer init.gpa.free(package_path);
    const package = try std.Io.Dir.cwd().readFileAlloc(init.io, package_path, init.gpa, .limited(1024 * 1024));
    defer init.gpa.free(package);
    var metadata = try std.json.parseFromSlice(std.json.Value, init.gpa, package, .{});
    defer metadata.deinit();
    const version = metadata.value.object.get("version") orelse return error.MissingVersion;
    if (version != .string or !std.mem.eql(u8, version.string, "1.3.27")) return error.TypeBoxVersionMismatch;
    const root = try std.fs.path.join(init.gpa, &.{ args[1], "build", "format" });
    defer init.gpa.free(root);
    var files: std.ArrayList(File) = .empty;
    defer {
        for (files.items) |file| {
            init.gpa.free(file.path);
            init.gpa.free(file.bytes);
        }
        files.deinit(init.gpa);
    }
    const dir = try std.Io.Dir.cwd().openDir(init.io, root, .{ .iterate = true });
    defer dir.close(init.io);
    var walker = try dir.walk(init.gpa);
    defer walker.deinit();
    while (try walker.next(init.io)) |entry| {
        if (entry.kind != .file or !std.mem.endsWith(u8, entry.path, ".mjs")) continue;
        const bytes = try dir.readFileAlloc(init.io, entry.path, init.gpa, .limited(1024 * 1024));
        errdefer init.gpa.free(bytes);
        const path = try init.gpa.dupe(u8, entry.path);
        errdefer init.gpa.free(path);
        for (path) |*byte| if (byte.* == '\\') {
            byte.* = '/';
        };
        var digest: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
        try files.append(init.gpa, .{ .path = path, .bytes = bytes, .sha256 = std.fmt.bytesToHex(digest, .lower) });
    }
    std.mem.sort(File, files.items, {}, less);
    const generated = try render(init.gpa, files.items);
    defer init.gpa.free(generated);
    if (check) {
        const current = try std.Io.Dir.cwd().readFileAlloc(init.io, args[2], init.gpa, .limited(8 * 1024 * 1024));
        defer init.gpa.free(current);
        if (!std.mem.eql(u8, generated, current)) return error.GeneratedPatternsDiffer;
    } else try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = args[2], .data = generated });
}
