//! Deterministic Unicode 17 grapheme table projection. Run from repository root.
const std = @import("std");
const Range = struct { first: u21, last: u21, property: []const u8 };
const Inputs = [_]struct { name: []const u8, hash: []const u8, table: []const u8 }{
    .{ .name = "GraphemeBreakProperty.txt", .hash = "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89", .table = "grapheme" },
    .{ .name = "DerivedCoreProperties.txt", .hash = "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08", .table = "indic" },
    .{ .name = "emoji-data.txt", .hash = "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b", .table = "pictographic" },
};
fn less(_: void, a: Range, b: Range) bool {
    return a.first < b.first;
}
pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len > 2 or (args.len == 2 and !std.mem.eql(u8, args[1], "--check"))) return error.InvalidArguments;
    var output: std.Io.Writer.Allocating = .init(init.gpa);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("//! Generated by tools/unicode_graphemes.zig from pinned Unicode 17.0.0 data.\n" ++
        "pub const Grapheme = enum { Other, CR, LF, Control, Extend, ZWJ, Regional_Indicator, Prepend, SpacingMark, L, V, T, LV, LVT };\n" ++
        "pub const Indic = enum { None, Consonant, Extend, Linker };\n" ++
        "pub fn Range(comptime T: type) type { return struct { first: u21, last: u21, property: T }; }\n");
    for (Inputs) |input| {
        const path = try std.fmt.allocPrint(init.gpa, "src/tui/unicode17/{s}", .{input.name});
        defer init.gpa.free(path);
        const data = try std.Io.Dir.cwd().readFileAlloc(init.io, path, init.gpa, .limited(4 * 1024 * 1024));
        defer init.gpa.free(data);
        var digest: [32]u8 = undefined;
        std.crypto.hash.sha2.Sha256.hash(data, &digest, .{});
        if (!std.mem.eql(u8, &std.fmt.bytesToHex(digest, .lower), input.hash)) return error.UnicodeInputHashMismatch;
        var ranges: std.ArrayList(Range) = .empty;
        defer ranges.deinit(init.gpa);
        var lines = std.mem.splitScalar(u8, data, '\n');
        while (lines.next()) |raw| {
            const line = std.mem.trim(u8, raw[0 .. std.mem.indexOfScalar(u8, raw, '#') orelse raw.len], " \t\r");
            if (line.len == 0) continue;
            var fields = std.mem.splitScalar(u8, line, ';');
            const code = std.mem.trim(u8, fields.next().?, " \t");
            var property = std.mem.trim(u8, fields.next() orelse return error.InvalidUnicodeData, " \t");
            if (std.mem.eql(u8, input.table, "indic")) {
                if (!std.mem.eql(u8, property, "InCB")) continue;
                property = std.mem.trim(u8, fields.next() orelse return error.InvalidUnicodeData, " \t");
            } else if (std.mem.eql(u8, input.table, "pictographic") and !std.mem.eql(u8, property, "Extended_Pictographic")) continue;
            const dot = std.mem.indexOf(u8, code, "..");
            const first = try std.fmt.parseInt(u21, if (dot) |i| code[0..i] else code, 16);
            const last = if (dot) |i| try std.fmt.parseInt(u21, code[i + 2 ..], 16) else first;
            try ranges.append(init.gpa, .{ .first = first, .last = last, .property = property });
        }
        std.mem.sort(Range, ranges.items, {}, less);
        try writer.print("// {s} SHA256 {s}\npub const {s} = [_]Range({s}){{\n", .{ input.name, input.hash, input.table, if (std.mem.eql(u8, input.table, "grapheme")) "Grapheme" else if (std.mem.eql(u8, input.table, "indic")) "Indic" else "bool" });
        for (ranges.items, 0..) |range, i| {
            if (i > 0 and range.first <= ranges.items[i - 1].last) return error.OverlappingUnicodeRanges;
            try writer.print("    .{{ .first = 0x{X}, .last = 0x{X}, .property = {s}{s} }},\n", .{ range.first, range.last, if (std.mem.eql(u8, input.table, "pictographic")) "" else ".", if (std.mem.eql(u8, input.table, "pictographic")) "true" else range.property });
        }
        try writer.writeAll("};\n");
    }
    const terminated = try init.gpa.dupeZ(u8, output.written());
    defer init.gpa.free(terminated);
    var ast = try std.zig.Ast.parse(init.gpa, terminated, .zig);
    defer ast.deinit(init.gpa);
    if (ast.errors.len != 0) return error.InvalidGeneratedUnicodeZig;
    const formatted = try ast.renderAlloc(init.gpa);
    defer init.gpa.free(formatted);
    const destination = "src/tui/unicode17/generated_graphemes.zig";
    if (args.len == 2) {
        const old = try std.Io.Dir.cwd().readFileAlloc(init.io, destination, init.gpa, .limited(4 * 1024 * 1024));
        defer init.gpa.free(old);
        if (!std.mem.eql(u8, old, formatted)) return error.StaleUnicodeProjection;
    } else try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = destination, .data = formatted });
}
