//! Project the pinned actual Source width-property capture into native data.
const std = @import("std");
fn less(_: void, a: []u16, b: []u16) bool {
    return std.mem.order(u16, a, b) == .lt;
}
pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len > 2 or (args.len == 2 and !std.mem.eql(u8, args[1], "--check"))) return error.InvalidArguments;
    const source = try std.Io.Dir.cwd().readFileAlloc(init.io, "src/tui/fixtures/input-width-original-6fb.json", init.gpa, .limited(16 * 1024 * 1024));
    defer init.gpa.free(source);
    var digest: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(source, &digest, .{});
    if (!std.mem.eql(u8, &std.fmt.bytesToHex(digest, .lower), "8d6a632c23a3aaa966c52f2ea11a41fd7803d0520f438c727df388aa784e849c")) return error.WidthCaptureHashMismatch;
    const parsed = try std.json.parseFromSlice(std.json.Value, init.gpa, source, .{});
    defer parsed.deinit();
    for (parsed.value.object.get("emojiInputs").?.array.items) |input| {
        const path = try std.fmt.allocPrint(init.gpa, "src/tui/unicode17/{s}", .{input.object.get("name").?.string});
        defer init.gpa.free(path);
        const bytes = try std.Io.Dir.cwd().readFileAlloc(init.io, path, init.gpa, .limited(1024 * 1024));
        defer init.gpa.free(bytes);
        std.crypto.hash.sha2.Sha256.hash(bytes, &digest, .{});
        if (!std.mem.eql(u8, &std.fmt.bytesToHex(digest, .lower), input.object.get("sha256").?.string)) return error.EmojiInputHashMismatch;
    }
    var output: std.Io.Writer.Allocating = .init(init.gpa);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("//! Generated by tools/unicode_width.zig from actual Source6fb / ICU78.2 / Unicode17 data.\n" ++
        "//! Capture SHA256 8d6a632c23a3aaa966c52f2ea11a41fd7803d0520f438c727df388aa784e849c.\n" ++
        "pub const Range = struct { first: u21, last: u21, flags: u8 };\npub const properties = [_]Range{\n");
    var previous: ?u21 = null;
    for (parsed.value.object.get("properties").?.array.items) |entry| {
        const first: u21 = @intCast(entry.object.get("first").?.integer);
        const last: u21 = @intCast(entry.object.get("last").?.integer);
        if (first > last or (previous != null and first <= previous.?)) return error.InvalidWidthPropertyRanges;
        previous = last;
        try writer.print("    .{{ .first = 0x{X}, .last = 0x{X}, .flags = {d} }},\n", .{ first, last, entry.object.get("value").?.integer });
    }
    try writer.writeAll("};\npub const emoji = [_][]const u16{\n");
    var emoji: std.ArrayList([]u16) = .empty;
    defer {
        for (emoji.items) |item| init.gpa.free(item);
        emoji.deinit(init.gpa);
    }
    for (parsed.value.object.get("emoji").?.array.items) |entry| {
        const text = try init.gpa.alloc(u16, entry.array.items.len);
        errdefer init.gpa.free(text);
        for (text, entry.array.items) |*unit, value| unit.* = @intCast(value.integer);
        try emoji.append(init.gpa, text);
    }
    std.mem.sort([]u16, emoji.items, {}, less);
    for (emoji.items, 0..) |text, index| {
        if (index > 0 and std.mem.eql(u16, text, emoji.items[index - 1])) return error.DuplicateEmojiSequence;
        try writer.writeAll("    &.{ ");
        for (text, 0..) |unit, part| {
            if (part > 0) try writer.writeAll(", ");
            try writer.print("0x{X}", .{unit});
        }
        try writer.writeAll(" },\n");
    }
    try writer.writeAll("};\n");
    const destination = "src/tui/unicode17/generated_width.zig";
    if (args.len == 2) {
        const old = try std.Io.Dir.cwd().readFileAlloc(init.io, destination, init.gpa, .limited(4 * 1024 * 1024));
        defer init.gpa.free(old);
        if (!std.mem.eql(u8, old, output.written())) return error.StaleWidthProjection;
    } else try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = destination, .data = output.written() });
}
