//! Native projection of pinned Unicode17/Source ICU78 normalization capture.
const std = @import("std");
const Pair = struct { first: u21, second: u21, value: u21 };
fn less(_: void, a: Pair, b: Pair) bool {
    return a.first < b.first or (a.first == b.first and a.second < b.second);
}
pub fn main(init: std.process.Init) !void {
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    if (args.len > 2 or (args.len == 2 and !std.mem.eql(u8, args[1], "--check"))) return error.InvalidArguments;
    const bytes = try std.Io.Dir.cwd().readFileAlloc(init.io, "src/tui/fixtures/word-normalization-original-6fb.json", init.gpa, .limited(8 * 1024 * 1024));
    defer init.gpa.free(bytes);
    var hash: [32]u8 = undefined;
    std.crypto.hash.sha2.Sha256.hash(bytes, &hash, .{});
    if (!std.mem.eql(u8, &std.fmt.bytesToHex(hash, .lower), "a421359ff0caa67472bc376087df39bb4e52ce80cf69ce99c14563dae3cd3d40")) return error.NormalizationInputHashMismatch;
    const parsed = try std.json.parseFromSlice(std.json.Value, init.gpa, bytes, .{});
    defer parsed.deinit();
    const unicode_data = try std.Io.Dir.cwd().readFileAlloc(init.io, "src/tui/unicode17/UnicodeData.txt", init.gpa, .limited(4 * 1024 * 1024));
    defer init.gpa.free(unicode_data);
    std.crypto.hash.sha2.Sha256.hash(unicode_data, &hash, .{});
    if (!std.mem.eql(u8, &std.fmt.bytesToHex(hash, .lower), parsed.value.object.get("unicodeData").?.object.get("sha256").?.string)) return error.UnicodeNormalizationDataHashMismatch;
    var output: std.Io.Writer.Allocating = .init(init.gpa);
    defer output.deinit();
    const writer = &output.writer;
    try writer.writeAll("//! Generated by tools/word_normalization_data.zig from pinned Source ICU78.2 / Unicode17 data.\n" ++
        "pub const Mapping = struct { cp: u21, text: []const u21 };\n" ++
        "pub const Combining = struct { cp: u21, value: u8 };\n" ++
        "pub const Composition = struct { first: u21, second: u21, value: u21 };\n" ++
        "pub const mappings = [_]Mapping{\n");
    for (parsed.value.object.get("mappings").?.array.items) |entry| {
        try writer.print("    .{{ .cp = 0x{X}, .text = &.{{ ", .{entry.object.get("codepoint").?.integer});
        for (entry.object.get("decomposition").?.array.items, 0..) |cp, index| {
            if (index != 0) try writer.writeAll(", ");
            try writer.print("0x{X}", .{cp.integer});
        }
        try writer.writeAll(" } },\n");
    }
    try writer.writeAll("};\npub const combining = [_]Combining{\n");
    for (parsed.value.object.get("combiningClasses").?.array.items) |entry| try writer.print("    .{{ .cp = 0x{X}, .value = {d} }},\n", .{ entry.object.get("codepoint").?.integer, entry.object.get("value").?.integer });
    try writer.writeAll("};\npub const compositions = [_]Composition{\n");
    var pairs: std.ArrayList(Pair) = .empty;
    defer pairs.deinit(init.gpa);
    var backwards: std.AutoHashMapUnmanaged(u21, void) = .empty;
    defer backwards.deinit(init.gpa);
    for (parsed.value.object.get("compositions").?.array.items) |entry| {
        const value: Pair = .{ .first = @intCast(entry.object.get("first").?.integer), .second = @intCast(entry.object.get("second").?.integer), .value = @intCast(entry.object.get("composite").?.integer) };
        try pairs.append(init.gpa, value);
        try backwards.put(init.gpa, value.second, {});
    }
    std.mem.sort(Pair, pairs.items, {}, less);
    for (pairs.items) |pair| try writer.print("    .{{ .first = 0x{X}, .second = 0x{X}, .value = 0x{X} }},\n", .{ pair.first, pair.second, pair.value });
    try writer.writeAll("};\npub const backwards = [_]u21{\n");
    const ordered = try init.gpa.alloc(u21, backwards.count());
    defer init.gpa.free(ordered);
    var iterator = backwards.keyIterator();
    var index: usize = 0;
    while (iterator.next()) |cp| {
        ordered[index] = cp.*;
        index += 1;
    }
    std.mem.sort(u21, ordered, {}, std.sort.asc(u21));
    for (ordered) |cp| try writer.print("    0x{X},\n", .{cp});
    try writer.writeAll("};\n");
    const terminated = try init.gpa.dupeZ(u8, output.written());
    defer init.gpa.free(terminated);
    var syntax = try std.zig.Ast.parse(init.gpa, terminated, .zig);
    defer syntax.deinit(init.gpa);
    if (syntax.errors.len != 0) return error.InvalidGeneratedNormalization;
    const canonical = try syntax.renderAlloc(init.gpa);
    defer init.gpa.free(canonical);
    const destination = "src/tui/icu78/generated_normalization.zig";
    if (args.len == 2) {
        const old = try std.Io.Dir.cwd().readFileAlloc(init.io, destination, init.gpa, .limited(4 * 1024 * 1024));
        defer init.gpa.free(old);
        if (!std.mem.eql(u8, old, canonical)) return error.StaleNormalizationProjection;
    } else try std.Io.Dir.cwd().writeFile(init.io, .{ .sub_path = destination, .data = canonical });
}
