const std = @import("std");
const host_mod = @import("extensions/host.zig");
test "host SDK snapshot crosses the real native owner pipe with owned retirement" {
    const gpa = std.testing.allocator;
    const io = std.testing.io;
    var temporary = std.testing.tmpDir(.{});
    defer temporary.cleanup();
    var root_buffer: [std.Io.Dir.max_path_bytes]u8 = undefined;
    var directory = try std.Io.Dir.cwd().openDir(io, ".", .{});
    defer directory.close(io);
    const root_count = try directory.realPath(io, &root_buffer);
    const executable = try std.fs.path.join(gpa, &.{ root_buffer[0..root_count], "zig-out", "bin", if (@import("builtin").os.tag == .windows) "pi-sdk-embedder.exe" else "pi-sdk-embedder" });
    defer gpa.free(executable);
    var buffer: [std.Io.Dir.max_path_bytes]u8 = undefined;
    const count = try temporary.dir.realPath(io, &buffer);
    const primary = try std.fs.path.join(gpa, &.{ buffer[0..count], "primary.mjs" });
    defer gpa.free(primary);
    const secondary = try std.fs.path.join(gpa, &.{ buffer[0..count], "secondary.mjs" });
    defer gpa.free(secondary);
    try temporary.dir.writeFile(io, .{ .sub_path = "primary.mjs", .data = "export default pi=>{};" });
    try temporary.dir.writeFile(io, .{ .sub_path = "secondary.mjs", .data = "import {ModelRuntime} from '@earendil-works/pi-coding-agent';export default async pi=>{const r=await ModelRuntime.create({refreshOnCreate:false});let id='alive';const model=()=>({provider:'host-copy',id,type:'chat',toJSON(){throw Error('no metadata callbacks')}});r.registerNativeProvider({id:'host-copy',auth:{apiKey:{resolve:async()=>({auth:{apiKey:'key'},source:'fixture'})}},getModels:()=>[model()],getAllModels:()=>[model()]});await r.getAvailable();await r.getAvailable();pi.registerCommand('replace',{handler:async()=>{id='replacement';await r.getAvailable();return {message:'replaced'}}})};" });
    var environment: std.process.Environ.Map = .init(gpa);
    defer environment.deinit();
    try environment.put("PATH", std.fs.path.dirname(executable).?);
    try environment.put("SystemRoot", "C:/Windows");
    try environment.put("WINDIR", "C:/Windows");
    try environment.put("PI_OFFLINE", "1");
    var host: host_mod.Host = .{ .gpa = gpa, .io = io, .script_backend = .native, .native_runtime_options = .{ .executable = executable, .environ_map = &environment } };
    defer host.deinit();
    try host.loadPath(primary);
    try host.loadPath(secondary);
    var copied = (try host.sdkAvailabilitySnapshot(gpa, 0)) orelse return error.MissingNativeSDKSnapshot;
    defer copied.deinit();
    try std.testing.expectEqual(@as(usize, 1), copied.available.len);
    try std.testing.expectEqualStrings("alive", copied.available[0].id);
    var command = (try host.executeCommand("replace", "")) orelse return error.MissingNativeSDKCommand;
    defer command.deinit(gpa);
    var replacement = (try host.sdkAvailabilitySnapshot(gpa, copied.runtime_id)) orelse return error.MissingNativeSDKSnapshot;
    defer replacement.deinit();
    try std.testing.expect(replacement.revision > copied.revision);
    try std.testing.expectEqualStrings("replacement", replacement.available[0].id);
    const removed = try host.native_group_runtime.?.invokeGroupRequest(1, "{\"kind\":\"group_remove_source\",\"ownerId\":2}", null);
    defer gpa.free(removed);
    var retired = try host.sdkAvailabilitySnapshot(gpa, copied.runtime_id);
    defer if (retired) |*value| value.deinit();
    try std.testing.expect(retired == null);
    try std.testing.expectEqualStrings("alive", copied.available[0].id);
}
